window.SEIKO={
"SB":"https://gwvabuxqufpqxdtqhmmy.supabase.co/storage/v1/object/public/cardapio/seiko/",
"nav":[["entradas-frias","Entradas Frias"],["entradas-quentes","Entradas Quentes"],["especiais","Especiais"],["sashimis","Sashimis"],["joys-temakis","Joys & Temakis"],["uramakis-hossomakis","Uramakis"],["hotrolls-combos","Hot Rolls"],["gunkan-sobremesas","Gunkan"],["bebidas","Bebidas"],["drinks","Drinks"]],
"fotos":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,67,68,70,72,73,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,93,94,95,96,100,101,102,103,104,105,106,107],
"items":{
"1":{"nm":"Sunomono Tradicional","pr":"15","mt":"150g","ds":"Tradicional salada japonesa de pepino fatiado finamente, marinada em molho sú e finalizada com gergelim torrado."},
"2":{"nm":"Sunomono Especial","pr":"22","mt":"150g","ds":"Uma releitura do clássico: pepino marinado em molho sú, com macarrão bifun e finalizado com lichia."},
"3":{"nm":"Gari","pr":"12","mt":"100g","ds":"Conserva de gengibre feita na casa."},
"4":{"nm":"Ceviche de Peixe Branco","pr":"40","mt":"200g","ds":"Peixe branco marinado em molho a base de laranja e limão, alho poró, tomate cereja, coentro e cebola roxa. Acompanha crispy de batata doce."},
"5":{"nm":"Ceviche de Frutos do Mar","pr":"69","mt":"200g","ds":"Camarões, polvo e peixe branco marinados em molho a base de laranja e limão, alho poró, tomate cereja, coentro e cebola roxa. Acompanha crispy de batata doce."},
"6":{"nm":"Baterá de Salmão","pr":"35","mt":"8 und","ds":"Sushi prensado de peixe, temperado com maionese especial e pimenta tailandesa. Finalizado com ovas, cebolinha e farofa de panko."},
"7":{"nm":"Sashimi Especial de Salmão","pr":"65","mt":"10 und","ds":"Fatias de salmão servidas com molho de ostra levemente apimentado, gergelim e quinoa, acompanhadas de crispy de batata doce, ovas e cebolinha."},
"8":{"nm":"Sashimi Salmão Codorna Trufado","pr":"35","mt":"4 und","ds":"Sashimi de salmão maçaricado com gema de ovo de codorna, ovas tobiko, salsa de trufas, cebolinha e flor de sal."},
"9":{"nm":"Crispy Rice","pr":"38","mt":"4 und","ds":"Arroz crocante, tartar de salmão ou atum trufado, gergelim, cebolinha, flor de sal e teriyaki. Opções: Atum ou Salmão."},
"10":{"nm":"Ussuzukuri de Peixe Branco","pr":"46","mt":"15 und","ds":"15 finas lâminas de peixe branco, molho cítrico a base de azeite, limão siciliano e flor de sal, finalizado com azeite trufado."},
"11":{"nm":"Ussuzukuri de Salmão","pr":"79","mt":"15 und","ds":"15 finas lâminas de salmão, temperadas com ovas tobiko, cebolinha, azeite trufado e flor de sal. Acompanha crispy de batata doce."},
"12":{"nm":"Ussuzukuri de Polvo","pr":"59","mt":"8 und","ds":"8 lâminas de polvo espanhol cozido lentamente, servido com molho cítrico, flor de sal e mix de quinoa crocante."},
"13":{"nm":"Shimeji na Manteiga","pr":"41","mt":"180g","ds":"Cogumelos shimeji salteados na manteiga com shoyu, finalizados com cebolinha. Adicional de Shari (100g): R$ 10."},
"14":{"nm":"Guioza Suíno","pr":"36","mt":"6 und","ds":"Pastéis de massa fina recheados com carne suína e legumes. Opção: frito ou a vapor."},
"15":{"nm":"Guioza de Salmão","pr":"45","mt":"6 und","ds":"Pastéis de massa fina recheados com salmão. Opção: frito ou a vapor."},
"16":{"nm":"Guioza Camarão","pr":"48","mt":"6 und","ds":"Pastéis de massa fina recheados com camarão, acompanhado com molho de curry e leite de côco. Opção: frito ou a vapor."},
"17":{"nm":"Salmon Ball","pr":"39","mt":"6 und","ds":"Bolinho de salmão artesanal, crocante por fora e macio por dentro, com tempero único da casa."},
"18":{"nm":"Shakebi","pr":"40","mt":"5 und","ds":"Deliciosos camarões empanados na panko, envoltos a cream cheese e em lâmina de salmão, finalizados com nosso tarê artesanal."},
"19":{"nm":"Camarão Empanado","pr":"30","mt":"5 und","ds":"Deliciosos camarões empanados na panko, temperados e finalizados com nosso tarê artesanal."},
"20":{"nm":"Edamame","pr":"41","mt":"150g","ds":"Vagens de soja levemente cozidas no vapor. Opções: Trufado ou Spicy."},
"21":{"nm":"Takoyaki","pr":"48","mt":"6 und","ds":"Bolinhos macios por dentro e levemente crocantes por fora, com massa especial recheada de polvo, finalizados com molho takoyaki, maionese japonesa, alga nori e lascas katsuobushi."},
"22":{"nm":"Harumaki Queijo","pr":"24","mt":"2 und","ds":"Rolinho primavera recheado com queijo, finalizado com mel."},
"23":{"nm":"Harumaki Suíno com Legumes","pr":"24","mt":"2 und","ds":"Rolinho primavera recheado com carne suína e legumes frescos."},
"24":{"nm":"Isca de Tilápia","pr":"49","mt":"250g","ds":"Iscas de tilápia empanadas e fritas."},
"25":{"nm":"Yakissoba Bovino","pr":"49","mt":"500g","ds":"Porção 500g (até 2 pessoas). Acompanha brócolis, couve flor, vagem, cebola, acelga, repolho roxo e cenoura."},
"26":{"nm":"Yakissoba Frango","pr":"40","mt":"500g","ds":"Porção 500g (até 2 pessoas). Acompanha brócolis, couve flor, vagem, cebola, acelga, repolho roxo e cenoura."},
"27":{"nm":"Yakissoba Camarão","pr":"55","mt":"500g","ds":"Porção 500g (até 2 pessoas). Acompanha brócolis, couve flor, vagem, cebola, acelga, repolho roxo e cenoura."},
"28":{"nm":"Yakissoba Vegetariano","pr":"35","mt":"500g","ds":"Porção 500g (até 2 pessoas). Acompanha brócolis, couve flor, vagem, cebola, acelga, repolho roxo e cenoura."},
"29":{"nm":"Teppanyaki de Salmão","pr":"109","mt":"300g","ds":"Deliciosa posta de salmão grelhada acompanhada de legumes salteados na manteiga e shoyu (cenoura, repolho roxo, repolho verde e acelga)."},
"30":{"nm":"Nigiris","pr":"90","mt":"6 und","ds":"Seleção especial do Chef."},
"31":{"nm":"Joys","pr":"90","mt":"6 und","ds":"Seleção especial do Chef."},
"32":{"nm":"Nigiri Vieira Trufada","pr":"39","mt":"2 und","ds":"Vieira canadense e alho negro trufado sobre arroz temperado."},
"33":{"nm":"Nigiri Unagi","pr":"59","mt":"2 und","ds":"Enguia importada levemente adocicada sobre arroz temperado."},
"34":{"nm":"Nigiri Atum Com Alho Negro","pr":"33","mt":"2 und","ds":"Atum maturado e alho negro trufado sobre arroz temperado."},
"35":{"nm":"Nigiri Polvo Espanhol","pr":"33","mt":"2 und","ds":"Polvo espanhol leve e aromático com toque de azeite trufado, cebolinha, ovas tobiko e flor de sal."},
"36":{"nm":"Nigiri Ebi Trufado","pr":"33","mt":"2 und","ds":"Camarão sobreposto por queijo brie maçaricado e mel trufado."},
"37":{"nm":"Hand Rolls","pr":"54","mt":"3 und","ds":"Trio de hand rolls (temakis abertos): atum spicy, camarão empanado com maionese especial, vieira trufada com ovas e flor de sal."},
"38":{"nm":"Salmão ou Atum na Crosta de Gergelim","pr":"49","mt":"5 und","ds":"Sashimis selados, acompanhado de cebola roxa caramelizada, ovas de tobiko, cebolinha e flor de sal."},
"39":{"nm":"Canapé Atum","pr":"33","mt":"2 und","ds":"Atum spice, maionese temperada, ovas de tobiko, cebolinha e flor de sal."},
"40":{"nm":"Crostini de Salmão","pr":"49","mt":"4 und","ds":"Salmão trufado, ovas de tobiko e creme azedo sobre pão crocante, com um delicioso toque de beringela defumada."},
"41":{"nm":"Chirashi","pr":"98","ds":"3 sashimis de salmão, 3 de peixe branco, 3 de polvo, 3 de atum e 2 de vieira. Acompanha alga wakame e ovas de tobiko sobre arroz temperado."},
"42":{"nm":"Temaki desmontado","pr":"49","ds":"Se divirta montando seu temaki! Atum spicy, salmão marinado no molho cítrico, flor de sal. Acompanha arroz temperado e folhas de nori."},
"43":{"nm":"Moriawase (Combo de Sashimis)","pr":"88","mt":"16 und","ds":"Seleção especial de sashimis de salmão, atum, peixe branco e polvo. Uma experiência completa e acessível para quem deseja variedade com qualidade."},
"44":{"nm":"Harasu com Ovas","pr":"42","mt":"6 und","ds":"Cortes nobres da parte mais macia e marmorizada do salmão. Textura amanteigada que derrete na boca, raspas de limão siciliano e cebolinha."},
"45":{"nm":"Sashimi Salmão","pr":"29","mt":"5 und"},
"46":{"nm":"Sashimi Atum","pr":"34","mt":"5 und"},
"47":{"nm":"Sashimi Vieira","pr":"54","mt":"5 und"},
"48":{"nm":"Sashimi Tako","pr":"39","mt":"5 und"},
"49":{"nm":"Sashimi Peixe Branco","pr":"26","mt":"5 und"},
"50":{"nm":"Nigiri Salmão","pr":"18"},
"51":{"nm":"Nigiri Atum","pr":"22"},
"52":{"nm":"Nigiri Ebi","pr":"24"},
"53":{"nm":"Nigiri Peixe Branco","pr":"16"},
"54":{"nm":"Nigiri Tako","pr":"22"},
"55":{"nm":"Nigiri Caramelizado","pr":"22","ds":"Salmão caramelizado, finalizado com flor de sal e raspas de limão siciliano sobre arroz temperado."},
"56":{"nm":"Nigiri Skin Lemon","pr":"18"},
"57":{"nm":"Nigiri Salmão Trufado","pr":"24","ds":"Barriga do salmão finalizada com azeite trufado, raspas de limão e flor de sal sobre arroz temperado."},
"58":{"nm":"Joy Salmão Tradicional","pr":"26","ds":"Lâmina de salmão enrolada no shari com topping de salmão e cream cheese, finalizada com cebolinha."},
"59":{"nm":"Joy Spicy Ebi","pr":"30","ds":"Lâmina de salmão enrolada no shari com topping de tempurá de camarão, sweet chilli, limão e especiarias."},
"60":{"nm":"Joy Codorna Trufado","pr":"30","ds":"Lâmina de salmão enrolada no shari, com toppings de ovo de codorna maçaricado, azeite trufado e ovas tobiko."},
"61":{"nm":"Joy Camarão","pr":"30","ds":"Lâmina de salmão enrolada no shari, com topping de cream cheese e camarão grelhado."},
"62":{"nm":"Joy Nikkei","pr":"28","ds":"Lâmina de salmão enrolada no shari, com topping de salmão marinado no limão, cebola roxa e especiarias."},
"63":{"nm":"Joy Geleia de Frutas Vermelhas","pr":"28","ds":"Lâmina de salmão enrolada no shari com topping de cream cheese e geleia fina de frutas vermelhas."},
"64":{"nm":"Joy Low Carb","pr":"33","ds":"Lâmina de salmão envolta a tartare de salmão e cream cheese, finalizada com cebolinha. (Sem arroz.)"},
"65":{"nm":"Philadelphia","pr":"33","ds":"Salmão e cream cheese."},
"66":{"nm":"Philadelphia sem arroz","pr":"38","ds":"Salmão e cream cheese, sem arroz."},
"67":{"nm":"Barriga de Salmão Trufado","pr":"44","ds":"Temaki com salmão em cubos, temperados com ovas tobiko, flor de sal e azeite trufado, finalizado com zest de limão siciliano."},
"68":{"nm":"Salmão Grelhado","pr":"33","ds":"Temaki com salmão grelhado, cream cheese, tarê, arroz e furikake."},
"69":{"nm":"Atum Spicy","pr":"38","ds":"Temaki com atum envolto a maionese picante, arroz e furikake."},
"70":{"nm":"Ebi","pr":"41","ds":"Temaki com camarão empanado, cream cheese, arroz, tarê e furikake."},
"71":{"nm":"Especial hot","pr":"38","ds":"Empanado e frito, cortado ao meio, finalizado com tarê artesanal, cream cheese, furikake e cebolinha. Opções: Salmão Cru ou Salmão Grelhado."},
"72":{"nm":"Nikkei","pr":"54","me":"R$ 32,50","ds":"Roll de camarão empanado com pepino, enrolado no arroz, coberto com atum, flor de sal e molho acevichado. Meia porção: R$ 32,50."},
"73":{"nm":"Philadelphia","pr":"42","me":"R$ 25,50","ds":"Clássico roll de salmão e cream cheese."},
"74":{"nm":"Salmão Crispy","pr":"50","me":"R$ 30","ds":"Roll de salmão e cream cheese, com topping de crispy de batata doce crocante e tarê artesanal. Meia porção: R$ 30."},
"75":{"nm":"Ebiten","pr":"54","me":"R$ 32,50","ds":"Roll de camarão empanado com cream cheese, sobreposto por fina lâmina de salmão, finalizado com teriyaki de vinho e molho acevichado. Meia porção: R$ 32,50."},
"76":{"nm":"Seiko","pr":"50","me":"R$ 30","ds":"Roll de salmão e cream cheese, sobreposto por fina lâmina de salmão maçaricada e crispy de couve. Meia porção: R$ 30."},
"77":{"nm":"Skin","pr":"40","me":"R$ 24","ds":"Roll de pele crocante de salmão, cream cheese e cebolinha. Meia porção: R$ 24."},
"78":{"nm":"Salmão Grelhado Especial","pr":"50","me":"R$ 30","ds":"Roll de salmão grelhado com zest de limão taiti e cream cheese, sobreposto por fina lâmina de salmão, amêndoas trituradas e tarê artesanal. Meia porção: R$ 30."},
"79":{"nm":"Salmão","pr":"36","me":"R$ 21,50","ds":"Enrolado fino de salmão."},
"80":{"nm":"Philadelphia","pr":"36","me":"R$ 21,50","ds":"Enrolado fino de salmão e cream cheese."},
"81":{"nm":"Salmão Grelhado","pr":"36","me":"R$ 21,50","ds":"Enrolado fino de salmão grelhado."},
"82":{"nm":"Kappamaki","pr":"32","me":"R$ 19","ds":"Enrolado fino de pepino. Meia porção: R$ 19."},
"83":{"nm":"Acelgamaki","pr":"44","me":"R$ 26","ds":"Maki enrolado na acelga, com topping de tartare de salmão, cream cheese e cebolinha. Meia porção: R$ 26."},
"84":{"nm":"Tekkamaki","pr":"44","me":"R$ 26","ds":"Enrolado fino de atum. Meia porção: R$ 26."},
"85":{"nm":"Spicy","pr":"50","me":"R$ 30","ds":"Enrolado fino de salmão, finalizado com cream cheese, sweet chilli, especiarias e limão. Meia porção: R$ 30."},
"86":{"nm":"Philadelphia","pr":"40","mt":"10 und","me":"R$ 24","ds":"Hot roll recheado com salmão e cream cheese. Meia porção: R$ 24."},
"87":{"nm":"Salmão Especial","pr":"50","mt":"10 und","me":"R$ 30","ds":"Hot roll com topping de tartar de salmão e cebolinha, finalizado com teriyaki e gergelim. Meia porção: R$ 30."},
"88":{"nm":"Harumi","pr":"50","mt":"10 und","me":"R$ 30","ds":"Hot roll com massa crocante, recheio de salmão, finalizado com cream cheese, tarê artesanal e especiarias. Meia porção: R$ 30."},
"89":{"nm":"Crispy de Couve","pr":"50","mt":"10 und","me":"R$ 30","ds":"Hot roll recheado com salmão e cream cheese, finalizado com crispy de couve e tarê artesanal. Meia porção: R$ 30."},
"90":{"nm":"Ebi","pr":"54","mt":"10 und","me":"R$ 32,50","ds":"Hot roll recheado com salmão, sobreposto com cream cheese e camarão grelhado, finalizado com tarê artesanal. Meia porção: R$ 32,50."},
"91":{"nm":"Big Hot","pr":"36","mt":"1 und","ds":"Crocante hot roll com tartare de salmão, crispy de couve, cream cheese, especiarias e tarê artesanal. Opções: Salmão Cru ou Salmão Grelhado."},
"92":{"nm":"Philadelphia 01","pr":"92","mt":"21 und","ds":"5 sashimis de salmão, 4 nigiris salmão, 2 joys tradicionais, 5 hossomakis philadelphia, 5 hot rolls philadelphia. (21 unidades)"},
"93":{"nm":"Philadelphia 02","pr":"149","mt":"33 und","ds":"10 sashimis salmão, 4 nigiris salmão, 4 joys tradicionais, 5 hossomakis philadelphia, 5 uramakis seiko, 5 hot rolls philadelphia. (33 unidades)"},
"94":{"nm":"Philadelphia 03","pr":"219","mt":"48 und","ds":"10 sashimis salmão, 4 nigiris salmão, 4 joys tradicionais, 10 uramakis philadelphia, 10 uramakis seiko, 10 hot rolls philadelphia. (48 unidades)"},
"95":{"nm":"Selection Duo","pr":"229","mt":"35 und","ds":"4 sashimis salmão, 4 sashimis polvo, 4 sashimis peixe do dia, 4 sashimis atum, 2 joys spicy ebi, 2 joys nikkei, 2 joys codorna trufado, 2 nigiris vieira trufada, 2 nigiris polvo, 2 nigiris caramelizados, 2 nigiris ebi, 5 uramakis ebiten. (35 unidades)"},
"96":{"nm":"Premium Duplo","pr":"199","mt":"35 und","ds":"5 sashimis salmão, 5 sashimis atum, 5 sashimis peixe branco, 2 nigiris salmão, 2 nigiris atum, 2 nigiris salmão maçaricado, 2 nigiris peixe branco, 5 hossomaki philadelphia, 5 uramaki philadelphia. (35 unidades)"},
"100":{"nm":"Nobre (Atum Maturado)","pr":"34","ds":"Cubos pequenos de atum, marinados no molho su, temperado com maionese spicy, cebolinha, furikake e flor de sal, envoltos em nori crocante."},
"101":{"nm":"Vieira","pr":"34","ds":"Vieira em cubos, ovas tobiko, azeite trufado e flor de sal, envoltos em nori crocante."},
"102":{"nm":"Salmão Tartare","pr":"29","ds":"Salmão levemente picante, cebolinha, gergelim e flor de sal, envoltos em nori crocante."},
"103":{"nm":"Atum Spicy","pr":"31","ds":"Atum levemente picante, ovas tobiko, cebolinha, gergelim e flor de sal, envoltos em nori crocante."},
"104":{"nm":"Salmão Grelhado","pr":"29","ds":"Salmão grelhado, zest de limão taiti, cream cheese, cebolinha e teriyaki, envoltos em nori crocante."},
"105":{"nm":"Brownie com Gelato","pr":"33","ds":"Brownie artesanal de castanhas, acompanhado de gelato e finalizado com caramelo salgado."},
"106":{"nm":"Harumaki Morango com Nutella","pr":"24","mt":"2 und","ds":"Rolinho primavera artesanal de morango com nutella."},
"107":{"nm":"Tempurá de sorvete","pr":"38","mt":"4 und","ds":"Sorvete de creme empanado em pão de ló e frito em massa crocante, acompanhado de calda especial."},
"108":{"nm":"Água sem Gás","pr":"5","mt":"500ml"},
"109":{"nm":"Água com Gás","pr":"6","mt":"500ml"},
"110":{"nm":"H2OH!","pr":"7","mt":"500ml"},
"111":{"nm":"Água Tônica","pr":"7","mt":"350ml"},
"112":{"nm":"Coca Cola","pr":"7"},
"113":{"nm":"Coca Cola Zero","pr":"7"},
"114":{"nm":"Guaraná Antárctica","pr":"7"},
"115":{"nm":"Guaraná Antárctica Zero","pr":"7"},
"116":{"nm":"Sprite","pr":"7"},
"117":{"nm":"Sprite Zero","pr":"7"},
"118":{"nm":"Fanta Uva","pr":"7"},
"119":{"nm":"Fanta Laranja","pr":"7"},
"120":{"nm":"Schweppes Citrus","pr":"7"},
"121":{"nm":"Guaraná Mineiro","pr":"7"},
"122":{"nm":"Guaraná Mineiro Zero","pr":"7"},
"123":{"nm":"Laranja","pr":"10","mt":"Natural 300ml"},
"124":{"nm":"Laranja c/ Morango","pr":"12","mt":"300ml"},
"125":{"nm":"Laranja c/ Amora","pr":"12","mt":"300ml"},
"126":{"nm":"Laranja c/ Maracujá","pr":"12","mt":"300ml"},
"127":{"nm":"Dell Vale Uva","pr":"7","mt":"310ml"},
"128":{"nm":"Dell Vale Pessego","pr":"7","mt":"310ml"},
"129":{"nm":"Heineken","pr":"13"},
"130":{"nm":"Heineken Ultimate","pr":"13"},
"131":{"nm":"Heineken Zero Álcool","pr":"13"},
"132":{"nm":"Stella Artois","pr":"13"},
"133":{"nm":"Stella Artois Pure Gold","pr":"13"},
"134":{"nm":"Corona","pr":"13"},
"135":{"nm":"Amstel Ultra","pr":"13"},
"136":{"nm":"Eisenbahn Pilsen","pr":"14"},
"137":{"nm":"Lagunita Ipa","pr":"23"},
"138":{"nm":"Campari","pr":"18","mt":"50ml"},
"139":{"nm":"Soju Chum Chum Lotte","pr":"18","mt":"50ml"},
"140":{"nm":"Sake Silver Thikara","pr":"17","mt":"80ml"},
"141":{"nm":"Sake Silver Thikara Garrafa","pr":"79","mt":"745ml"},
"142":{"nm":"Sake Gold Thikara","pr":"20","mt":"80ml"},
"143":{"nm":"Sake Gold Thikara Garrafa","pr":"89","mt":"745ml"},
"144":{"nm":"Sake Gold Black","pr":"35","mt":"80ml"},
"145":{"nm":"Sake Gold Black Garrafa","pr":"349","mt":"750ml"},
"146":{"nm":"Whisky Johnnie Walker Red Label","pr":"25"},
"147":{"nm":"Whisky Johnnie Walker Black Label","pr":"30"},
"148":{"nm":"Whisky Old Parr 12 anos","pr":"25","mt":"50ml"},
"149":{"nm":"Whisky Jack Daniels","pr":"28","mt":"50ml"},
"150":{"nm":"Tequila Jose Cuervo Ouro","pr":"25","mt":"50ml"},
"151":{"nm":"Whisky Japonês Hibiki Harmony Suntory","pr":"95","mt":"50ml"},
"152":{"nm":"Koimainu","pr":"25","ds":"Chá mate torrado com suco de laranja, limão-taiti e purê de yuzu criam um coquetel refrescante, cítrico e levemente amargo, com sutis notas tostadas."},
"153":{"nm":"Hatsuhinode","pr":"33","ds":"Chá de hibisco com cravo, lichia, laranja e flor de sabugueiro resultam em um coquetel floral e frutado, de doçura equilibrada, acidez suave e leve picância."},
"154":{"nm":"Soda Italiana","pr":"18","ds":"Bebida refrescante preparada com água com gás, gelo e xarope saborizado. Sabores: amora, cranberry, flor de sabugueiro, gengibre, lichia, maçã verde, maracujá e morango."},
"155":{"nm":"Negroni Umeboshi","pr":"39","ds":"Gin, campari infusionado com ameixa umeboshi e vermute Cinzano criam um coquetel amargo e complexo, com dulçor sutil e um toque fermentado, um clássico com personalidade japonesa."},
"156":{"nm":"Akai Kadan (Bloody Mery)","pr":"42","ds":"Suco de tomate, limão-siciliano, soju e especiarias japonesas revelam um coquetel de umami elevado, condimentado e refrescante. Ousado, com clarificação que surpreende."},
"157":{"nm":"Benzaiten","pr":"35","ds":"Suco de lichia, hibisco e nossa vodka Citron artesanal. Acompanha bolha de aromas. Coquetel leve, aveludado e floral."},
"158":{"nm":"Kekkon Shoya","pr":"38","ds":"Redução de catuaba, gin e espumante, acompanhado de bolha de aroma. Sabores sofisticados, frisante, cítrico levemente adocicado."},
"159":{"nm":"Cozumel","pr":"29","ds":"Cerveja Heineken, limão, mel e sal."},
"160":{"nm":"Caipi's","pr":"31","ds":"A clássica e refrescante combinação brasileira: limões frescos macerados com açúcar, equilibrando acidez e doçura, finalizada com cachaça ou vodka. Opções: cachaça ou vodka. Sabores: abacaxi, amora, frutas tropicais, frutas vermelhas, kiwi, maracujá ou morango."},
"161":{"nm":"Sakerinha","pr":"31","ds":"A versão oriental da clássica caipirinha: limões frescos macerados, combinados com saquê suave e gelo, resultando em uma bebida leve, cítrica e extremamente refrescante. Sabores: abacaxi, amora, frutas tropicais, frutas vermelhas, kiwi, maracujá ou morango."},
"162":{"nm":"Aperol Spritz","pr":"34","ds":"Aperol, espumante brut e água com gás formam um coquetel amargo e frisante, com um final cítrico e doce."},
"163":{"nm":"Basil Smash","pr":"31","ds":"Gin, manjericão, limão-siciliano e xarope de açúcar resultam em um coquetel refrescante, herbal e equilibrado, ideal para dias quentes."},
"164":{"nm":"Cosmopolitan","pr":"31","ds":"Vodka infusionada com limão-siciliano, limão-taiti, licor artesanal de laranja e xarope de cranberry criam um coquetel levemente ácido, frutado e sofisticado."},
"165":{"nm":"Fitzgerald","pr":"31","ds":"Clássico contemporâneo, leve e sofisticado. Gin, suco de limão-siciliano fresco, xarope de açúcar e gotas de bitter de angostura resultam em um drink cítrico, refrescante e equilibrado, com delicado toque aromático."},
"166":{"nm":"G&T","pr":"31","ds":"Gin e água tônica compõem um coquetel seco, aromático e levemente amargo, clássico e atemporal."},
"167":{"nm":"Moscow Mule","pr":"30","ds":"Vodka, xarope de gengibre, limão-taiti, água com gás e espuma cítrica formam um coquetel picante, cremoso e efervescente."},
"168":{"nm":"Negroni","pr":"34","ds":"Clássico da coquetelaria italiana: gin, Campari e vermute tinto em partes iguais. Elegante, de sabor intenso, com notas cítricas e herbais e amargor marcante, servido com gelo e casca de laranja. Opções: tradicional ou com café."}
},
"secs":[{"id":"entradas-frias","t":"Entradas Frias","note":"","num":"01","b":[["plain",[1,2,3,4,5,6]],["panel",[7,8,9],"right",1],["sub","Ussuzukuris",""],["panel",[10,11,12],"left",1]]},{"id":"entradas-quentes","t":"Entradas Quentes","note":"","num":"02","b":[["panel",[13,14,15,16],"right",2],["plain",[17,18,19,20,21,22,23]],["sub","Pratos Quentes",""],["panel",[24,25,26,27,28,29],"left",1]]},{"id":"especiais","t":"Especiais Seiko","note":"","num":"03","b":[["panel",[30,31,32,33,34,35,36],"right",2],["panel",[37,38,39,40,41,42],"left",1]]},{"id":"sashimis","t":"Sashimis","note":"","num":"04","b":[["panel",[43,44],"left",1],["plain",[45,46,47,48,49]],["sub","Nigirizushis","2 unidades"],["panel",[50,51,52,53,54,55,56,57],"right",2]]},{"id":"joys-temakis","t":"Joys","note":"4 unidades","num":"05","b":[["panel",[58,59,60,61,62,63,64],"right",1],["sub","Temakis","1 unidade"],["panel",[65,66,67,68,69,70,71],"left",1]]},{"id":"uramakis-hossomakis","t":"Uramakis","note":"10 unidades","num":"06","b":[["panel",[72,73,74,75,76,77,78],"right",3],["sub","Hossomakis","10 unidades"],["panel",[79,80,81,82,83,84,85],"left",3]]},{"id":"hotrolls-combos","t":"Hot Rolls","note":"","num":"07","b":[["panel",[86,87,88,89,90,91],"right",2],["sub","Combos",""],["panel",[92,93,94,95,96],"left",3]]},{"id":"gunkan-sobremesas","t":"Gunkan","note":"2 unidades","num":"08","b":[["panel",[100,101,102,103,104],"right",3],["sub","Sobremesas",""],["panel",[105,106,107],"left",3]]},{"id":"bebidas","t":"Bebidas","note":"","num":"09","b":[["subs","Águas",""],["plain",[108,109,110,111]],["subs","Refrigerantes Lata","310ml"],["plain",[112,113,114,115,116,117,118,119,120,121,122]],["subs","Sucos",""],["plain",[123,124,125,126,127,128]],["subs","Cervejas Long Neck",""],["plain",[129,130,131,132,133,134,135,136,137]],["subs","Doses",""],["plain",[138,139,140,141,142,143,144,145,146,147,148,149,150,151]]]},{"id":"drinks","t":"Drinks","note":"","num":"10","b":[["subs","Mocktails","não alcoólicos"],["plain",[152,153,154]],["subs","Coquetéis Assinatura",""],["panel",[155,156,157,158],"right",1],["subs","Coquetéis Clássicos",""],["plain",[159,160,161,162,163,164,165,166,167,168]]]}]
};